name: Firestore

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/firestore.yml'
      - 'FirebaseFirestoreUI/**'
      - 'test.sh'
      - 'FirebaseFirestoreUI.podspec'
      - 'Package.swift'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/firestore.yml'
      - 'FirebaseFirestoreUI/**'
      - 'test.sh'
      - 'FirebaseFirestoreUI.podspec'
      - 'Package.swift'

  workflow_dispatch:

jobs:
  xcodebuild:
    name: xcodebuild
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: |
          cd FirebaseFirestoreUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseFirestoreUI
  spm:
    name: spm
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: List
        run: |
          xcodebuild -list
      - name: Build
        run: |
          xcodebuild -scheme FirebaseFirestoreUI -sdk iphonesimulator  -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 Pro'
  pod:
    name: pod lib lint
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: gem install bundler; bundle install
      - name: Build
        run: |
          bundle exec pod lib lint FirebaseFirestoreUI.podspec
