name: Google Auth

on:
  push:
    branches: [ master ]
    paths:
      - 'FirebaseAuthUI/**'
      - 'FirebaseAuthUI.podspec'
      - '.github/workflows/googleauth.yml'
      - 'FirebaseGoogleAuthUI/**'
      - 'test.sh'
      - 'FirebaseGoogleAuthUI.podspec'
  pull_request:
    branches: [ master ]
    paths:
      - 'FirebaseAuthUI/**'
      - 'FirebaseAuthUI.podspec'
      - '.github/workflows/googleauth.yml'
      - 'FirebaseGoogleAuthUI/**'
      - 'test.sh'
      - 'FirebaseGoogleAuthUI.podspec'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: |
          cd FirebaseGoogleAuthUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseGoogleAuthUI
  spm:
    name: spm
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: List
        run: |
          xcodebuild -list
      - name: Build
        run: |
          xcodebuild -scheme FirebaseGoogleAuthUI -sdk iphonesimulator  -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 Pro'
  pod:
    name: pod lib lint
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        run: gem install bundler; bundle install
      - name: Build
        run: |
          bundle exec pod lib lint FirebaseGoogleAuthUI.podspec \
            --include-podspecs=FirebaseAuthUI.podspec --skip-import-validation
